// Autogenerated from Pigeon (v23.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import "Pigeon.h"

#if TARGET_OS_OSX
#import <FlutterMacOS/FlutterMacOS.h>
#else
#import <Flutter/Flutter.h>
#endif

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSArray <id> *wrapResult(id result, FlutterError *error) {
  if (error) {
    return @[
      error.code ?: [NSNull null], error.message ?: [NSNull null], error.details ?: [NSNull null]
    ];
  }
  return @[ result ?: [NSNull null] ];
}

static id GetNullableObjectAtIndex(NSArray <id> *array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}

@interface FLTPigeonPigeonCodecReader : FlutterStandardReader
@end
@implementation FLTPigeonPigeonCodecReader
- (nullable id)readValueOfType:(UInt8)type {
    switch (type) {
        default:
            return [super readValueOfType:type];
    }
}
@end

@interface FLTPigeonPigeonCodecWriter : FlutterStandardWriter
@end
@implementation FLTPigeonPigeonCodecWriter
- (void)writeValue:(id)value {
    {
        [super writeValue:value];
    }
}
@end

@interface FLTPigeonPigeonCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation FLTPigeonPigeonCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
    return [[FLTPigeonPigeonCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
    return [[FLTPigeonPigeonCodecReader alloc] initWithData:data];
}
@end

NSObject <FlutterMessageCodec> *FLTGetPigeonCodec(void) {
  static FlutterStandardMessageCodec *sSharedObject = nil;
    static dispatch_once_t sPred = 0;
    dispatch_once(&sPred, ^{
        FLTPigeonPigeonCodecReaderWriter *readerWriter = [[FLTPigeonPigeonCodecReaderWriter alloc] init];
        sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
    });
  return sSharedObject;
}

void SetUpFLTFlutterPrintApi(id <FlutterBinaryMessenger> binaryMessenger,
                             NSObject <FLTFlutterPrintApi> *api) {
    SetUpFLTFlutterPrintApiWithSuffix(binaryMessenger, api, @"");
}

void SetUpFLTFlutterPrintApiWithSuffix(id <FlutterBinaryMessenger> binaryMessenger,
                                       NSObject <FLTFlutterPrintApi> *api,
                                       NSString *messageChannelSuffix) {
    messageChannelSuffix = messageChannelSuffix.length > 0
                           ? [NSString stringWithFormat:@".%@", messageChannelSuffix] : @"";
  /// 打印文本数据
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
              initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_plugin_ble_printer.FlutterPrintApi.printText", messageChannelSuffix]
        binaryMessenger:binaryMessenger
                     codec:FLTGetPigeonCodec()];
      if (api) {
          NSCAssert([api respondsToSelector:@selector(printTextText:error:)],
                    @"FLTFlutterPrintApi api (%@) doesn't respond to @selector(printTextText:error:)",
                    api);
          [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
              NSArray <id> *args = message;
              NSString *arg_text = GetNullableObjectAtIndex(args, 0);
              FlutterError *error;
              [api printTextText:arg_text error:&error];
              callback(wrapResult(nil, error));
          }];
      } else {
          [channel setMessageHandler:nil];
    }
  }
  /// 打印图片
  /// https://flutter.cn/docs/development/ui/assets-and-images#loading-flutter-assets-in-ios
  /// flutter:
  ///   assets:
  ///     - icons/heart.png
  /// filePath = assets/icons/heart.png
  ///
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
              initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_plugin_ble_printer.FlutterPrintApi.printImage", messageChannelSuffix]
        binaryMessenger:binaryMessenger
                     codec:FLTGetPigeonCodec()];
      if (api) {
          NSCAssert([api respondsToSelector:@selector(printImageX:y:filePath:error:)],
                    @"FLTFlutterPrintApi api (%@) doesn't respond to @selector(printImageX:y:filePath:error:)",
                    api);
          [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
              NSArray <id> *args = message;
              NSInteger arg_x = [GetNullableObjectAtIndex(args, 0) integerValue];
              NSInteger arg_y = [GetNullableObjectAtIndex(args, 1) integerValue];
              NSString *arg_filePath = GetNullableObjectAtIndex(args, 2);
              FlutterError *error;
              [api printImageX:arg_x y:arg_y filePath:arg_filePath error:&error];
              callback(wrapResult(nil, error));
          }];
      } else {
      [channel setMessageHandler:nil];
    }
  }
    /// 打印二维码
    /// ommand PrinterHelper.BARCODE：⽔平⽅向
    ///        PrinterHelper.VBARCODE：垂直⽅向
    ///
    /// x     ⼆维码的起始横坐标。（单位：dot）
    ///
    /// y     ⼆维码的起始纵坐标。（单位：dot）
    ///
    /// M     QR的类型：
    ///       1：普通类型
    ///       2：在类型1的基础上增加了个别的符号
    ///
    /// U     单位宽度/模块的单元⾼度,范围是1到32默认为6
    ///
    /// data  ⼆维码的数据
    {
        FlutterBasicMessageChannel *channel =
                [[FlutterBasicMessageChannel alloc]
                        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_plugin_ble_printer.FlutterPrintApi.printQrCode", messageChannelSuffix]
                     binaryMessenger:binaryMessenger
                               codec:FLTGetPigeonCodec()];
        if (api) {
            NSCAssert([api respondsToSelector:@selector(printQrCodeCommand:x:y:M:U:data:error:)],
                      @"FLTFlutterPrintApi api (%@) doesn't respond to @selector(printQrCodeCommand:x:y:M:U:data:error:)",
                      api);
            [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
                NSArray <id> *args = message;
                NSString *arg_command = GetNullableObjectAtIndex(args, 0);
                NSString *arg_x = GetNullableObjectAtIndex(args, 1);
                NSString *arg_y = GetNullableObjectAtIndex(args, 2);
                NSString *arg_M = GetNullableObjectAtIndex(args, 3);
                NSString *arg_U = GetNullableObjectAtIndex(args, 4);
                NSString *arg_data = GetNullableObjectAtIndex(args, 5);
                FlutterError *error;
                [api printQrCodeCommand:arg_command x:arg_x y:arg_y M:arg_M U:arg_U data:arg_data error:&error];
                callback(wrapResult(nil, error));
            }];
        } else {
            [channel setMessageHandler:nil];
        }
    }
    {
        FlutterBasicMessageChannel *channel =
                [[FlutterBasicMessageChannel alloc]
                        initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_plugin_ble_printer.FlutterPrintApi.printBarcode", messageChannelSuffix]
                     binaryMessenger:binaryMessenger
                               codec:FLTGetPigeonCodec()];
        if (api) {
            NSCAssert(
                    [api respondsToSelector:@selector(printBarcodeCommand:type:width:ratio:height:x:y:undertext:number:size:offset:data:error:)],
                    @"FLTFlutterPrintApi api (%@) doesn't respond to @selector(printBarcodeCommand:type:width:ratio:height:x:y:undertext:number:size:offset:data:error:)",
                    api);
            [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
                NSArray <id> *args = message;
                NSString *arg_command = GetNullableObjectAtIndex(args, 0);
                NSString *arg_type = GetNullableObjectAtIndex(args, 1);
                NSString *arg_width = GetNullableObjectAtIndex(args, 2);
                NSString *arg_ratio = GetNullableObjectAtIndex(args, 3);
                NSString *arg_height = GetNullableObjectAtIndex(args, 4);
                NSString *arg_x = GetNullableObjectAtIndex(args, 5);
                NSString *arg_y = GetNullableObjectAtIndex(args, 6);
                BOOL arg_undertext = [GetNullableObjectAtIndex(args, 7) boolValue];
                NSString *arg_number = GetNullableObjectAtIndex(args, 8);
                NSString *arg_size = GetNullableObjectAtIndex(args, 9);
                NSString *arg_offset = GetNullableObjectAtIndex(args, 10);
                NSString *arg_data = GetNullableObjectAtIndex(args, 11);
                FlutterError *error;
                [api printBarcodeCommand:arg_command type:arg_type width:arg_width ratio:arg_ratio height:arg_height x:arg_x y:arg_y undertext:arg_undertext number:arg_number size:arg_size offset:arg_offset data:arg_data error:&error];
                callback(wrapResult(nil, error));
            }];
        } else {
            [channel setMessageHandler:nil];
        }
    }
  /// 控制打印机走纸到标签缝隙（标缝）
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
              initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_plugin_ble_printer.FlutterPrintApi.form", messageChannelSuffix]
        binaryMessenger:binaryMessenger
                     codec:FLTGetPigeonCodec()];
      if (api) {
          NSCAssert([api respondsToSelector:@selector(formWithError:)],
                    @"FLTFlutterPrintApi api (%@) doesn't respond to @selector(formWithError:)",
                    api);
          [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
              FlutterError *error;
              [api formWithError:&error];
              callback(wrapResult(nil, error));
          }];
      } else {
          [channel setMessageHandler:nil];
      }
  }
    /// 打印输出
    {
        FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
              initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_plugin_ble_printer.FlutterPrintApi.print", messageChannelSuffix]
        binaryMessenger:binaryMessenger
                     codec:FLTGetPigeonCodec()];
        if (api) {
            NSCAssert([api respondsToSelector:@selector(printWithError:)],
                      @"FLTFlutterPrintApi api (%@) doesn't respond to @selector(printWithError:)",
                      api);
            [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
                FlutterError *error;
                [api printWithError:&error];
                callback(wrapResult(nil, error));
            }];
        } else {
            [channel setMessageHandler:nil];
        }
    }
    /// 获取状态
    {
        FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
              initWithName:[NSString stringWithFormat:@"%@%@", @"dev.flutter.pigeon.flutter_plugin_ble_printer.FlutterPrintApi.getEndStatus", messageChannelSuffix]
        binaryMessenger:binaryMessenger
                     codec:FLTGetPigeonCodec()];
        if (api) {
            NSCAssert([api respondsToSelector:@selector(getEndStatusSecondTimeout:error:)],
                      @"FLTFlutterPrintApi api (%@) doesn't respond to @selector(getEndStatusSecondTimeout:error:)",
                      api);
            [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
                NSArray <id> *args = message;
                NSInteger arg_secondTimeout = [GetNullableObjectAtIndex(args, 0) integerValue];
                FlutterError *error;
                NSNumber *output = [api getEndStatusSecondTimeout:arg_secondTimeout error:&error];
                callback(wrapResult(output, error));
            }];
        } else {
            [channel setMessageHandler:nil];
        }
    }
}
