// Autogenerated from Pigeon (v9.2.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by FLTFlutterPrintApi.
NSObject<FlutterMessageCodec> *FLTFlutterPrintApiGetCodec(void);

@protocol FLTFlutterPrintApi
/// 打印文本数据
- (void)printTextText:(NSString *)text error:(FlutterError *_Nullable *_Nonnull)error;
/// 打印图片
/// https://flutter.cn/docs/development/ui/assets-and-images#loading-flutter-assets-in-ios
/// flutter:
///   assets:
///     - icons/heart.png
/// filePath = assets/icons/heart.png
///
- (void)printImageX:(NSNumber *)x y:(NSNumber *)y filePath:(NSString *)filePath error:(FlutterError *_Nullable *_Nonnull)error;
/// 控制打印机走纸到标签缝隙（标缝）
- (void)formWithError:(FlutterError *_Nullable *_Nonnull)error;
/// 打印输出
- (void)printWithError:(FlutterError *_Nullable *_Nonnull)error;
/// 获取状态
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber *)getEndStatusSecondTimeout:(NSNumber *)secondTimeout error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTFlutterPrintApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<FLTFlutterPrintApi> *_Nullable api);

NS_ASSUME_NONNULL_END
