// Autogenerated from Pigeon (v23.0.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

#import <Foundation/Foundation.h>

@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN


/// The codec used by all APIs.
NSObject<FlutterMessageCodec>
*

FLTGetPigeonCodec(void);

@protocol FLTFlutterPrintApi
/// 打印文本数据
- (void)printTextText:(NSString *)text error:(FlutterError *_Nullable *_Nonnull)error;
/// 打印图片
/// https://flutter.cn/docs/development/ui/assets-and-images#loading-flutter-assets-in-ios
/// flutter:
///   assets:
///     - icons/heart.png
/// filePath = assets/icons/heart.png
///
- (void)printImageX:(NSInteger)x y:(NSInteger)y filePath:(NSString *)filePath error:(FlutterError *_Nullable

*_Nonnull)
error;

/// 打印二维码
/// ommand PrinterHelper.BARCODE：⽔平⽅向
///        PrinterHelper.VBARCODE：垂直⽅向
///
/// x     ⼆维码的起始横坐标。（单位：dot）
///
/// y     ⼆维码的起始纵坐标。（单位：dot）
///
/// M     QR的类型：
///       1：普通类型
///       2：在类型1的基础上增加了个别的符号
///
/// U     单位宽度/模块的单元⾼度,范围是1到32默认为6
///
/// data  ⼆维码的数据
- (void)printQrCodeCommand:(NSString *)command x:(NSString *)x y:(NSString *)y M:(NSString *)M U:(NSString *)U data:(NSString *)data error:(FlutterError *_Nullable

*_Nonnull)
error;

- (void)printBarcodeCommand:(NSString *)command type:(NSString *)type width:(NSString *)width ratio:(NSString *)ratio height:(NSString *)height x:(NSString *)x y:(NSString *)y undertext:(BOOL)undertext number:(NSString *)number size:(NSString *)size offset:(NSString *)offset data:(NSString *)data error:(FlutterError *_Nullable

*_Nonnull)
error;
/// 控制打印机走纸到标签缝隙（标缝）
- (void)formWithError:(FlutterError *_Nullable *_Nonnull)error;
/// 打印输出
- (void)printWithError:(FlutterError *_Nullable *_Nonnull)error;
/// 获取状态
///
/// @return `nil` only when `error != nil`.
- (nullable NSNumber

*)getEndStatusSecondTimeout:(NSInteger)
secondTimeout error
:(
FlutterError *_Nullable
*_Nonnull)
error;
@end

extern void SetUpFLTFlutterPrintApi(id <FlutterBinaryMessenger> binaryMessenger,
                                    NSObject <FLTFlutterPrintApi> *_Nullable api);

extern void SetUpFLTFlutterPrintApiWithSuffix(id <FlutterBinaryMessenger> binaryMessenger,
                                              NSObject <FLTFlutterPrintApi> *_Nullable api,
                                              NSString *messageChannelSuffix);

NS_ASSUME_NONNULL_END
